CREATE TABLE check_ins(
    ch_id INT NOT NULL PRIMARY KEY IDENTITY,
    ch_createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    att_id VARCHAR(255) NOT NULL,
    CONSTRAINT ch_att_id_fkey FOREIGN KEY (att_id) REFERENCES ATTENDEES(att_id) ON DELETE RESTRICT ON UPDATE CASCADE
);